#-*- coding:utf-8 -*-

#通用错误[1-100]


#注册[101-200]
EC_REGISTER_PHONENYM_TYPE_ERROR = 101
ER_REGISTER_PHONENYM_TYPE_ERROR = "手机号格式错误，请重新输入"
EC_REGISTER_USERID_REPEAT = 102
ER_REGISTER_USERID_REPEAT = "该账号已被注册"
EC_REGISTER_IDCARD_TYPE_ERROR = 103
ER_REGISTER_IDCARD_TYPE_ERROR = "身份证号格式错误，请重新输入"
EC_REGISTER_PASSWORD_TYPE_ERROR = 104
ER_REGISTER_PASSWORD_TYPE_ERROR = "密码格式错误，请重新输入"


# 登录【201-300】
EC_LOGIN_USERID_ERROR = 201
ER_LOGIN_USERID_ERROR = "账号不存在，请重新输入"
EC_LOGIN_PASSWORD_ERROR = 202
ER_LOGIN_PASSWORD_ERROR = "密码错误，请重新输入"
EC_LOGIN_STATUS_ERROR = 203
ER_LOGIN_STATUS_ERROR = "账号状态存在问题，拒绝登录"
