#-*- coding:utf-8 -*-

#通用错误[1-100]
EC_LOGIN_INVALID = 1
ER_LOGIN_INVALID = "登录失效请重新登录"

#注册[101-200]
EC_REGISTER_PHONENYM_TYPE_ERROR = 101
ER_REGISTER_PHONENYM_TYPE_ERROR = "手机号格式错误，请重新输入"
EC_REGISTER_USERID_REPEAT = 102
ER_REGISTER_USERID_REPEAT = "该账号已被注册"
EC_REGISTER_IDCARD_TYPE_ERROR = 103
ER_REGISTER_IDCARD_TYPE_ERROR = "身份证号格式错误，请重新输入"
EC_REGISTER_PASSWORD_TYPE_ERROR = 104
ER_REGISTER_PASSWORD_TYPE_ERROR = "密码格式错误，请重新输入"


# 登录【201-300】
EC_LOGIN_USERID_ERROR = 201
ER_LOGIN_USERID_ERROR = "账号不存在，请重新输入"
EC_LOGIN_PASSWORD_ERROR = 202
ER_LOGIN_PASSWORD_ERROR = "密码错误，请重新输入"
EC_LOGIN_STATUS_ERROR = 203
ER_LOGIN_STATUS_ERROR = "账号状态存在问题，拒绝登录"

# 商城 【301-400】
EC_SHOP_VERSION_LOW = 301
ER_SHOP_VERSION_LOW = "商城版本过低， 请刷新重试"
EC_SHOP_BUY_LIST_NOT_EXIST = 302
ER_SHOP_BUY_LIST_NOT_EXIST = "商品未上架"
EC_SHOP_BUY_PROP_NOT_EXIST = 303
ER_SHOP_BUY_PROP_NOT_EXIST = "商品不存在"
EC_SHOP_BUY_CLIENT_VERSION_LOW = 304
ER_SHOP_BUY_CLIENT_VERSION_LOW = "客户端版本过低，请更新后重试"
EC_SHOP_BUY_INVENTORY_NOT_ENOUGH = 305
ER_SHOP_BUY_INVENTORY_NOT_ENOUGH = "商品库存不足"
EC_SHOP_BUY_MONEY_NOT_ENOUGH = 306
ER_SHOP_BUY_MONEY_NOT_ENOUGH = "货币不足"

# 任务 【401-500】
EC_TASK_ID_NOT_EXISTS = 401
ER_TASK_ID_NOT_EXISTS = "任务ID不存在, 非法访问任务"
EC_TASK_NOT_FINISH = 402
ER_TASK_NOT_FINISH = "非法访问，任务未完成，无法领取"
EC_TASK_REWARD_PRESENT_ERROR = 403
ER_TASK_REWARD_PRESENT_ERROR = "任务奖励发放失败"
EC_TASK_SIGN_TYPE_ERROR = 404
ER_TASK_SIGN_TYPE_ERROR = "签到类型错误"
